### ISSUE TITLE
Aqui pra mim não tem funcionado.

### ISSUE THREAD

**Issue by recoverjp** [victorratts13/bet365-api#1]
Victor, esse script ainda roda normalmente pra você?
Aqui não consigo realizar o login.

**Comment by victorratts13** [comment]
> Victor, esse script ainda roda normalmente pra você?
> Aqui não consigo realizar o login.

faz tempo que não atualizo este repositório, sugiro utilizar os mais atuais que mantenho como [sport-score](https://github.com/victorratts13/sport-score) .

caso tenha duvidas, pode entrar em contato diretamente comigo no telegram @VictorRatts
