### ISSUE TITLE
Nova API ou forma de recuperar os dados

### ISSUE THREAD

**Issue by ryok90** [victorratts13/bet365-api#2]
Opa, tranquilo?
Queria saber se por um acaso você chegou a descobrir outras formas de logar e recuperar informações da conta automatizada.
Atualmente nesses endpoints ao que me parece o IP é bloqueado após o primeiro acesso.

Tem conhecimento de maneiras alternativas?

**Comment by victorratts13** [comment]
Boa noite amigo.
Bem, a principio, todas as rodas da bet365 foram alteradas. Porem, algumas rotas como a de login, permanecem funcionais. Utilizar axios ou outros frameworks de requisições não vão ajudar muito. A maneira mais viavel é usar puppetter.

Eu criei uma biblioteca simples onde uso em meus projetos de scraping para obter dados da bet365 e fazer login.
[puppetter-get-iframe](https://www.npmjs.com/package/puppeteer-get-iframe) espero que ajude

**Comment by ryok90** [comment]
Eu estava utilizando puppeteer a princípio porém para manipular a própria página e acabei tendo o bloqueio.
Eu preciso de umas funcionalidades básicas do Bet365.
Você teria disponibilidade para uma consultoria superficial específica?
Se sim, posso te contactar pelo próprio e-mail que está no seu perfil?

**Comment by victorratts13** [comment]
@victorratts Telegram

**Comment by ryok90** [comment]
Muito obrigado amigo!
